version: '3.0'
services:
  nginx:
    image: nginx:latest
    ports:
      - 90:80
    volumes:
      - .:/var/www/mvc
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - backend

  php:
    container_name: mvc_web
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/mvc
    links:
      - mysql
    networks:
      - backend
    environment:
        ENV_DEV: ${ENV_DEV}
        MYSQL_DB: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_PORT: ${MYSQL_PORT}

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: mvc_mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_HOST=${MYSQL_HOST}
#      - MYSQL_PORT=${MYSQL_PORT}
    environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    env_file:
#      - ./.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
#      - data:/var/lib/mysql
#      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend: